<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-Q8UQAUDS" ignored="0" name="Test1" tests="2" failures="2" timestamp="2022-07-11T18:19:06 IST" time="4.491" errors="0">
  <testcase name="main1" time="4.395" classname="listner1.Sample1">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at listner1.Sample1.main1(Sample1.java:28)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- main1 -->
  <testcase name="main1" time="4.447" classname="listner1.Sample1">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at listner1.Sample3.screenshot(Sample3.java:17)
at listner1.Sample2.onTestFailure(Sample2.java:23)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- main1 -->
</testsuite> <!-- Test1 -->
